### ISSUE TITLE
Expanded table collapses when method for event is called

### ISSUE THREAD

**Issue by devmare** [IvanJosipovic/BlazorTable#114]
I am using buttons in a nested table (DetailTemplate) to Add/Edit/Delete items. When the onclick method is called the expanded table collapses.

**Comment by IvanJosipovic** [comment]
Could you please post a small code snipped that reproduces this issue?

**Comment by devmare** [comment]
I've modified BlazorTable.Sample.Shared -> Index.razor to show this (had to add axtension .txt to attach file here)
[Index.razor.txt](https://github.com/IvanJosipovic/BlazorTable/files/4548110/Index.razor.txt)

**Comment by IvanJosipovic** [comment]
Hey,

Thanks for the repro, this issue should be fixed in [1.9.0](https://github.com/IvanJosipovic/BlazorTable/releases/tag/v1.9.0)
