### ISSUE TITLE
Reason for TableRowClass being an Expression?

### ISSUE THREAD

**Issue by rdadkins** [IvanJosipovic/BlazorTable#119]
I have a quick design question. Why is `TableRowClass` configured to be `Expression<Func<TableItem, string>>` when it is just going to be compiled into `Func<TableItem, string>` and reused?

This is being brought up because my table rows could be 1 of 4 different classes and making an Expression turned into a nested ternary expression.

**Comment by IvanJosipovic** [comment]
Hey,

The Table Row functionality was provided through a [PR](https://github.com/IvanJosipovic/BlazorTable/pull/42) 
I'd be happy to consider a change to this functionality if it makes life easier.

**Comment by IvanJosipovic** [comment]
Released in https://github.com/IvanJosipovic/BlazorTable/releases/tag/v1.11.0
