### ISSUE TITLE
Column CSS?

### ISSUE THREAD

**Issue by qfyra** [IvanJosipovic/BlazorTable#143]
The [roadmap](https://github.com/IvanJosipovic/BlazorTable/issues/39) has a checkmark in front of "Column CSS", but I don't see any way to actually use it. Is there a way? If so, how?

**Comment by conficient** [comment]
The column CSS is set using the `Class` attribute in a `Column`m e.g.
```html
<Table TableItem="PersonData" Items="data" PageSize="15">
   <Column TableItem="PersonData" Title="Id" Field="@(x => x.id)" Class="text-info" /> 
</Table>
```
Note the `Class="text-info"`

Hope this helps!
