### ISSUE TITLE
Table from dynamic datasets

### ISSUE THREAD

**Issue by gregorvilkner** [IvanJosipovic/BlazorTable#145]
I have list of string headers and well behaved list of list of string rows. Is there a way to get this going with this excellent control? Somehow loop through the columns, instead of using a strongly typed dataset? Cheers, Gregor

**Comment by kwhv23** [comment]
If I understand your question correctly, I opened an issue a few days ago about a similar desire to have a dynamic table and was able to find a solution.

The difference for my stuff is I'm iterating over all of the fields in a class rather than a list of strings.

All of my code should be in here:
https://github.com/IvanJosipovic/BlazorTable/issues/144

**Comment by gregorvilkner** [comment]
argh... I give up. I tried to use a List of ExpandoObject, but can't get that expression for Field to work.
I think a code snippet for List of JObject or for dynamic would really help. Thanks for the response earlier.

`    <Table TableItem="JObject" Items="data" PageSize="100">`
`        @for (int i = 0; i < data.First().Properties().Count(); i++)`
`        {`
`            string aHeader = data.First().Properties().ToArray()[i].Name;`
`            <Column TableItem="JObject" Title="@aHeader" Field="@(x=>x[aHeader].ToString())" />`
`        }`
`        <Pager ShowPageNumber="true" ShowTotalCount="true" />`
`    </Table>`

**Comment by kwhv23** [comment]
No problem! Sorry I couldn't have been more help.

As far as I saw, calling ToString() in the expression body makes it not a memberexpression. When I tried things like that I would get errors telling me that a conversion from "some expression type" to a unary expression couldn't be done. 

I was able to track down how and why this was happening in the BlazorTable source code, but I had to convert everything to member expressions was the main thing.

I hope you're able to get everything working! I'm interested in seeing it working too.

**Comment by gregorvilkner** [comment]
lol. yes. no. i didn't get it to work. the code snippet is basically where i'm stuck. don't know how to make that expression work... no worries. Thanks for you feedback. Cheers, Gregor

**Comment by kwhv23** [comment]
@IvanJosipovic Hey, I know this is someone else's issue, but I had a similar thing that I was trying to do <a href="https://github.com/IvanJosipovic/BlazorTable/issues/144">on an issue that I opened (#144)</a>, but I ended up solving it myself. 

I did have to download the repo and make some changes, but I didn't think they'd be useful to anyone else so I never made a pull request (hell, I didn't even make a fork, I just have it sitting on a local machine). Would you like me to re-open this issue if you're thinking about trying to start supporting dynamic datasets?

**Comment by IvanJosipovic** [comment]
Hey @kwhv23,

I have started a new [branch](https://github.com/IvanJosipovic/BlazorTable/tree/Feat145) and used your awesome code as a starting point. You can give it a test. It works fine for regular generic objects. However, it doesn't yet work with JObject.
Usage example, https://github.com/IvanJosipovic/BlazorTable/blob/d94795bb6ed05d8175283fa60fa6cd193789eccf/src/BlazorTable.Sample.Shared/Pages/DynamicColumn.razor#L6

I'm debating on how to add support for JObject without adding a dependency to Newtonsoft.Json.

I may make another package (BlazorTable.DynamicColumnsJObject) which just deals with this problem.

**Comment by IvanJosipovic** [comment]
Version 1.13 added a DynamicColumns component.

```
<Table TableItem="PersonData" Items="data" PageSize="15" ShowSearchBar="true">
    <DynamicColumns TableItem="PersonData" Sortable="true" Filterable="true" />
    <Pager ShowPageNumber="true" ShowTotalCount="true" ShowPageSizes="true" />
</Table>
```
