### ISSUE TITLE
System.NullReferenceException when using Globalsearch in a template column with related data

### ISSUE THREAD

**Issue by tkennedy13** [IvanJosipovic/BlazorTable#146]
I'm using version 1.11.1 and I get  an error when I have a template column that uses shows a field from a related model. The error is `System.NullReferenceException: 'Object reference not set to an instance of an object.'` 

Here is what the offending column look like:

```
<Column TableItem="Model" Title="Region" Field="@(x => x.Region.Name)" Sortable="true" Filterable="true" Width="5%">
	<Template>
		@(context.Region != null ? context.Region.Name : string.Empty)
	</Template>
</Column> 
```

Here is my entire table definition:

```
<Table TableItem="Model" Items="_models" PageSize="50" ColumnReorder="true" ShowSearchBar="true" RowClickAction="RowClick" SelectionType="SelectionType.Single"
	   TableClass="table table-hover table-sm" TableHeadClass="thead-light">
	<Column TableItem="Model" Title="Name" Field="@(x => x.Name)" Sortable="true" Filterable="true" DefaultSortColumn="true" Width="10%" />
	<Column TableItem="Model" Title="Phone Number" Field="@(x => x.PhoneNumber)" Sortable="true" Filterable="false" Width="5%" />
	<Column TableItem="Model" Title="Email" Field="@(x => x.EmailAddress)" Sortable="true" Filterable="false" Width="10%">
		<Template>
			<a href="mailto:@context.EmailAddress">@context.EmailAddress</a>
		</Template>
	</Column> 
	<Column TableItem="Model" Title="Locality" Field="@(x => x.Locality)" Sortable="true" Filterable="true" Width="5%" />
   <Column TableItem="Model" Title="Region" Field="@(x => x.Region.Name)" Sortable="true" Filterable="true" Width="5%">
		<Template>
			@(context.Region != null ? context.Region.Name : string.Empty)
		</Template>
	</Column>                
	<LoadingDataTemplate>
		<div class="text-center">
			<p><em>Loading...</em></p>
		</div>
	</LoadingDataTemplate>
	<Pager ShowPageNumber="true" ShowTotalCount="true" />
</Table>
```

Everything works great if I comment out the "Region" column.

_Originally posted by @tkennedy13 in https://github.com/IvanJosipovic/BlazorTable/issues/135#issuecomment-649041668_

**Comment by kwhv23** [comment]
I'm not the owner of the repo, but when I was looking at the source code I think it still trying to access the related entity (which would fail when the Region is null in this case, obviously) when it runs the global search. 

Essentially, AFAIK it doesn't search based on the text in the template, but rather the data in the field you pass in.

I bet you could load your data into a DTO where you don't have a related entity, just a primitive field "RegionName" that way you won't run into null reference exceptions.

**Comment by IvanJosipovic** [comment]
Hi, please try the latest [release 1.12.0](https://github.com/IvanJosipovic/BlazorTable/releases/tag/v1.12.0).

**Comment by tkennedy13** [comment]
I installed version 1.12 and it works great! Thank you for the fix and thank you for the package it has been very helpful.
