### ISSUE TITLE
Footer data is incorrect when using Footer and DetailTemplate

### ISSUE THREAD

**Issue by darrenowen2020** [IvanJosipovic/BlazorTable#152]
![image](https://user-images.githubusercontent.com/67629947/87789292-b6453700-c836-11ea-8f25-6913bbc26a98.png)

<Table TableItem="ViewInvoiceGroup" Items="viewInvoiceGroups" PageSize="10" ColumnReorder="true" ShowFooter="true">
		<Column TableItem="ViewInvoiceGroup" Title="Description" Field="@(x => x.InvoiceDescription)" Sortable="true" Width="10%" SetFooterValue="Totals" />
		<Column TableItem="ViewInvoiceGroup" Title="Gross" Field="@(x => x.InvoiceGross)" Sortable="true" Width="10%" Aggregate="AggregateType.Sum" Format="C" />
		<Column TableItem="ViewInvoiceGroup" Title="VAT" Field="@(x => x.InvoiceVAT)" Sortable="true" Width="10%" Aggregate="AggregateType.Sum" Format="C" />
		<Column TableItem="ViewInvoiceGroup" Title="Total" Field="@(x => x.InvoiceNet)" Sortable="true" Width="10%" Aggregate="AggregateType.Sum" Format="C" />
		<DetailTemplate TableItem="ViewInvoiceGroup">
			<Table TableItem="InvoiceView" Items="@getGroup(context.InvoiceDescription)" PageSize="10" ColumnReorder="true" ShowFooter="true">
				<Column TableItem="InvoiceView" Title="Site" Field="@(x => x.SiteName)" Sortable="true" Width="10%" DefaultSortColumn="true" />
				<Column TableItem="InvoiceView" Title="Supplier" Field="@(x => x.SupplierName)" Sortable="true" Width="10%" />
				<Column TableItem="InvoiceView" Title="Reference" Field="@(x => x.InvoiceReference)" Sortable="true" Width="10%" DefaultSortColumn="true" />
				<Column TableItem="InvoiceView" Title="Description" Field="@(x => x.InvoiceDescription)" Sortable="true" Width="10%" />
				<Column TableItem="InvoiceView" Title="Payment Type" Field="@(x => x.InvoicePaymentDescription)" Sortable="true" Width="10%" DefaultSortColumn="true" />
				<Column TableItem="InvoiceView" Title="Gross" Field="@(x => x.InvoiceGross)" Format="C" Sortable="true" Width="10%" DefaultSortColumn="true" />
				<Column TableItem="InvoiceView" Title="Vat" Field="@(x => x.InvoiceVAT)" Format="C" Sortable="true" Width="10%" DefaultSortColumn="true" />
				<Column TableItem="InvoiceView" Title="Total" Field="@(x => x.InvoiceNet)" Format="C" Sortable="true" Width="10%" />
			</Table>
		</DetailTemplate>
		<Pager ShowPageNumber="true" ShowTotalCount="true" />
	</Table>

As you can see in the screen shot the new column that is added for the '+' puts the footer data in the wrong column.

**Comment by conficient** [comment]
Pretty simple fix 
https://github.com/IvanJosipovic/BlazorTable/pull/155 has been requested

**Comment by IvanJosipovic** [comment]
Fix has been released in version 1.12.0. Thanks @conficient!
