### ISSUE TITLE
Images srcs

### ISSUE THREAD

**Issue by fenriquepc** [IvanJosipovic/BlazorTable#154]
Hi,

I've included BlazorTable on a Blazor project that is hosted on a Github project page. As the page url is "user.github.id/projectname/", the images of the component are missing because of the absolute path on the src attributes "/_content/BlazorTable/images/sort-desc.png". 

Maybe the first "/" of the path should be removed: "_content/BlazorTable/images/sort-desc.png". This way, <base> path is used and  the component images are properly visualized.

**Comment by conficient** [comment]
The absolute path is required to work in the normal usage where the Blazor app is at the root url. For example, in a page at `https://example.com/customer/orders` requesting an image at '_content/BlazorTable/images/sort-desc.png' would return an invalid src of `https://example.com/customer/orders/_content/BlazorTable/images/sort-desc.png` 

I think we might need to see if something needs to amended in relation to [App base path](
https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-3.1&tabs=visual-studio#app-base-path)

**Comment by conficient** [comment]
@fenriquepc can you confirm if your app has 
```
<base href="/CoolApp/">
```
in the file `wwwroot/index.html` ?

**Comment by IvanJosipovic** [comment]
Thanks @conficient. Please reopen this issue if its still not solved.
