### ISSUE TITLE
_content files reference the root of the site

### ISSUE THREAD

**Issue by rjwii** [IvanJosipovic/BlazorTable#169]
When using BlazorTable on a site in the location of http://domain/site/ the _content files are incorrectly referenced as http://domain/_content rather than http://domain/site/_content.
The root cause of this is Table.razor referencing the site root in the HTML, e.g. < img src="/_content/BlazorTable/images/sort-desc.png" />.

**Comment by IvanJosipovic** [comment]
Hey, can you see if https://github.com/IvanJosipovic/BlazorTable/issues/154 resolves your issue?

**Comment by IvanJosipovic** [comment]
Can you pleases try version 1.13.1 and let me know if this issue is resolved?
