### ISSUE TITLE
[Bug] image issues with different base href

### ISSUE THREAD

**Issue by chrgraefe** [IvanJosipovic/BlazorTable#172]
**Describe the bug**
I recognized a problem with different <base href=..> in index.html in different environments.
For local development I use <base href="/" /> , but in QA environment I use <base href="/calc/" />
In QA and the images for sorting and filtering were not found and the broser gets a 404 error.
Is this a known issue?

**To Reproduce**
none

**Expected behavior**
images/icons visible in both environments

**Comment by IvanJosipovic** [comment]
Can you pleases try version 1.13.1 and let me know if this issue is resolved?

**Comment by chrgraefe** [comment]
It works like a dream! Thank you!
