### ISSUE TITLE
[Feat] New property "AutoGenerateColumns"

### ISSUE THREAD

**Issue by chrgraefe** [IvanJosipovic/BlazorTable#177]
**Describe the solution you'd like**
I want request a feature similar to the  ASP.NET WebForms Gridview "AutoGenerateColumns" property.
This property is of type Boolean and if it is set to true, all columns will be generated automatically with default values.

kind reards
Christian

**Comment by IvanJosipovic** [comment]
Version 1.13 added a DynamicColumns component.

<Table TableItem="PersonData" Items="data" PageSize="15" ShowSearchBar="true">
    <DynamicColumns TableItem="PersonData" Sortable="true" Filterable="true" />
    <Pager ShowPageNumber="true" ShowTotalCount="true" ShowPageSizes="true" />
</Table>
