### ISSUE TITLE
[Bug] V 1.14.0 - missing dependency "Localization"

### ISSUE THREAD

**Issue by christopher-bonitz** [IvanJosipovic/BlazorTable#213]
**Describe the bug**
After upgrading my Nuget to1.14.0 the project no longer works in runtime, I'm having a pure web-assembly app.
The error goes away if I rollback the version to 1.13.1, and re-appears if I redo the upgrade, so its consistent.

I have noticed the added "Localization" dependency in the new version, I'm trying to keep my footprint small, so I wonder what is added in the new version.

I'm having the same error on multiple tables, so it fails consistently as well.

**To Reproduce**
* Nuget install 1.14.0
* Clean solution
* Build

Reverse this to rollback.

``` Web Console error
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot provide a value for property 'Localization' on type 'BlazorTable.Table`1[[***.Models.User, ***.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'. There is no registered service of type 'Microsoft.Extensions.Localization.IStringLocalizer`1[BlazorTable.Components.Localization]'.
System.InvalidOperationException: Cannot provide a value for property 'Localization' on type 'BlazorTable.Table`1[[***.Models.User, ***.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'. There is no registered service of type 'Microsoft.Extensions.Localization.IStringLocalizer`1[BlazorTable.Components.Localization]'.
```

**Expected behavior**
To not have critical exceptions

**Comment by IvanJosipovic** [comment]
Hey,

The release 1.14.0 has a braking change due to the addition of Localozation. Please review the readme.

- Add call to Program.cs or Startup.cs
  - Services.AddBlazorTable();

**Comment by christopher-bonitz** [comment]
> 
> 
> Hey,
> 
> The release 1.14.0 has a braking change due to the addition of Localozation. Please review the readme.
> 
>     * Add call to Program.cs or Startup.cs
>       
>       * Services.AddBlazorTable();

Great! that did the trick.
I implemented the following line in my Program.cs file
builder.Services.AddBlazorTable();

Thanks for the help
