### ISSUE TITLE
How to format currency and symbol of money?

### ISSUE THREAD

**Issue by citsole** [IvanJosipovic/BlazorTable#214]
Dear BlazorTable is greate components. First i thank you very much
Please help me how to format currency number and how to remove or chanage symbol  of money?
Thank you for help me.

**Comment by IvanJosipovic** [comment]
Hey,

There are two options, the column has a Format Parameter. Additionally, you can override the Template do what ever you want with the object,

[String Format Options](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings)

```
<Table TableItem="PersonData" Items="data" PageSize="15">
    <Column TableItem="PersonData" Title="Price" Field="@(x => x.price)" Sortable="true" Filterable="true" Width="10%" Format="C" Align="Align.Right" />
    <Column TableItem="PersonData" Title="Price" Field="@(x => x.price)" Sortable="true" Filterable="true" Width="20%">
        <Template>
            @context.price.ToString("D")
        </Template>
    </Column>
    <Pager ShowPageNumber="true" ShowTotalCount="true" />
</Table>
```

**Comment by citsole** [comment]
Thank you a lot i can do now. My country use format: Format="N"
