### ISSUE TITLE
Redundant TableItem="AnyClass" attribute

### ISSUE THREAD

**Issue by chrgraefe** [IvanJosipovic/BlazorTable#22]
Why is the "TableItem" attribute redundant in the markup?

![image](https://user-images.githubusercontent.com/4922897/68112602-f73c2c00-fef1-11e9-862b-7f2212dac5ef.png)

Is it really necessary?

**Comment by IvanJosipovic** [comment]
I believe its needed until https://github.com/aspnet/AspNetCore/issues/7268 is fixed.
