### ISSUE TITLE
[Feat] Ability to save/restore user's hidden column settings

### ISSUE THREAD

**Issue by CrewNerd** [IvanJosipovic/BlazorTable#235]
**Describe the solution you'd like**
My app's table will have 16 columns, but most users will want to have only 4-8 visible. I'd like to be able to save their "hidden column" settings to local storage so I can restore them when the app is launched.

**Comment by irushabh** [comment]
Hello,

I am also looking for same solutions for my project. I want to save column visibility settings to database and load from database when user visit that same grid next time.

Let me know if I can help you and we can find some way together.

**Comment by CrewNerd** [comment]
I think the existing object model may provide what we want. There's a "Visible" (get/set) property on the column. and the elements of the Columns property on the table can be reordered. I'm going to experiment with this.

**Comment by irushabh** [comment]
Yeah. I have tried that. I have also setup that property as [Parameter] and trying to set value externally, but somehow it adding extra columns, also it set by default visible = false to all columns.

**Comment by irushabh** [comment]
Hello,

Any luck with your try?

Let me know if you want to take a look of my code.!!

**Comment by CrewNerd** [comment]
Setting the "Visible" property of the columns as desired in the OnAfterRender method seems to work for me. I have looked into saving/restoring the column order yet.

**Comment by irushabh** [comment]
Hello,

if you can share your code for rendering Column visibility on OnAfterRender method, that would be good.

Thanks,
Rush

**Comment by CrewNerd** [comment]
Here's the relevant code:

```
    protected override void OnAfterRender(bool firstRender)
    {
        if (firstRender)
        {
            RestoreTableColumns();
        }
    }

    private void SaveTableColumns()
    {
        if (ViewerState.Table != null)
        {
            localStorage.SetItem("columnVisibility", table.Columns.Select((c) => c.Visible).ToArray());
        }
    }

    private void RestoreTableColumns()
    {
        if (localStorage.ContainKey("columnVisibility") && table != null)
        {
            var columnVisibility = localStorage.GetItem<bool[]>("columnVisibility");
            for (int i = 0; i < table.Columns.Count && i < columnVisibility.Length; i++)
            {
                table.Columns[i].Visible = columnVisibility[i];
            }
        }
    }
```

Then, you just have to call SaveTableColumns wherever it makes sense for you, since there's no event (that I know of) when the user adds or removes a column. For me, the table is in a tab group, so I restore/save the columns when the user moves to/from the tab with the table.

**Comment by irushabh** [comment]
Hello,

Great work..!!! 


Finally, I did it. Thank you so much. I am going to share my code below for your reference:

// below code when you change columns visibility and click on Close Popover button. (Table.razor.cs)
  protected void ColumnVisibilitySave()
  {
      VisibilityMenuOpen = false; 
      OnSaveGridVisibility.Invoke(Columns);
  }


// below code when you receive on Parent Component (index.razor.cs)
protected void GetColumnsSetup(List<IColumn<PersonData>> selcols)
  {
      myDBListCols = selcols;
  }


// Now, Loading on OnAfterRender Method.
Just like you did on your code snippet above.


Let me know if you don't understand my code.

Thanks
Rush

**Comment by irushabh** [comment]
Hello,

Will you please share me full code that you did for loading columns visibility and saving to local storage. 

I just having an issues with columns reordering OnAfterRenderAsync Method.

Thanks,
Rush

**Comment by CrewNerd** [comment]
I haven't worked on the column reordering yet, but I see that the order of items in the Columns property *does* change when the columns are reordered, so it seems like it should be possible to re-sort them in OnAfterRender according to their prior ordering.

For local storage I just used Blazored.LocalStorage.

**Comment by CrewNerd** [comment]
I got column reordering working as well. I save the visibility and index of each column as separate dictionaries, mapping the column title to the visibility flag and desired index, respectively. There was one weirdness - the casing of the column titles was getting messed with somewhere, so I mapped everything to lower case to get around that. Here's the relevant section of my code:

```
private const string VisibilityByTitleKey = "visibilityByTitle";
private const string IndexByTitleKey = "indexByTitle";

private void SaveTableColumns()
{
    if (table != null)
    {
	localStorage.SetItem(IndexByTitleKey, table.Columns.ToDictionary((c) => c.Title.ToLower(), (c) => table.Columns.IndexOf(c)));
	localStorage.SetItem(VisibilityByTitleKey, table.Columns.ToDictionary((c) => c.Title.ToLower(), (c) => c.Visible));
    }
}

private void RestoreTableColumns()
{
    if (localStorage.ContainKey(VisibilityByTitleKey) && table != null)
    {
	var visibilityByTitle = localStorage.GetItem<Dictionary<string, bool>>(VisibilityByTitleKey);
	table.Columns.ForEach((c) => c.Visible = visibilityByTitle[c.Title.ToLower()]);
    }

    if (localStorage.ContainKey(IndexByTitleKey) && table != null)
    {
	var indexByTitle = localStorage.GetItem<Dictionary<string, int>>(IndexByTitleKey);
	table.Columns.Sort((a, b) => indexByTitle[a.Title.ToLower()].CompareTo(indexByTitle[b.Title.ToLower()]));
    }
}
```

**Comment by irushabh** [comment]
Hello,

That is good news. However, this solution is good for Dictionary object. Since I am using List<Model> object to get all columns from Database. this solution won't work for me.

if you could convert this dictionary solution to List<Model>, that would be a big help. Let me know if you required my side of code to review.

Thanks,
Rush
