### ISSUE TITLE
How can I load a page with a table in EditMode?

### ISSUE THREAD

**Issue by chrgraefe** [IvanJosipovic/BlazorTable#25]
How can I load a page with a table in EditMode?

**Comment by IvanJosipovic** [comment]
Have you tried executing ITable.ToggleEditMode() in the OnInitialized Event?

See this example on how to use the ToggleEditMode(), https://github.com/IvanJosipovic/BlazorTable/blob/master/src/BlazorTable.Sample/Pages/EditMode.razor
