### ISSUE TITLE
Paging

### ISSUE THREAD

**Issue by KevinBurton** [IvanJosipovic/BlazorTable#267]
I would like to allow for paging. 
For many of my data sources there is a lot of data. Some tables have a million row or more. I would not like to download a million rows for this component to page through. I would like to intercept API calls that need more data and translate that request into a request for just a page worth of data. So even though I have a million rows, I never transfer more than a page worth of data over the network at one time.

**Comment by IvanJosipovic** [comment]
Can you see if this example solves your problem? https://github.com/IvanJosipovic/BlazorTable/blob/master/src/BlazorTable.Sample.Shared/Pages/ServerSideData.razor

**Comment by KevinBurton** [comment]
I haven’t digested it yet, but this seems to do the trick. Thank you. The
key seems to be the ‘Records’ property. This has to be a like a class that
contains something like a count, page number, and page size. Correct?

**Comment by KevinBurton** [comment]
Sorry about that. I looked further in the code and could see a custom data
loader. Exactly what I was looking for. Thank you.

**Comment by KevinBurton** [comment]
Just a clarification: The comment indicates that it is server side data. And the using statements pull in server side components. But I don't see any specific server side calls. It all seems to make HttpClient requests to get the data?
