### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by qfyra** [IvanJosipovic/BlazorTable#315]
I've noted a lack of updates recently, as well as a lack of answers to questions in the Issues list. Is the project still alive and well? Considering the times we're living in, here's hoping y'all are staying healthy :)

**Comment by conficient** [comment]
@IvanJosipovic I've also noticed a lack of updates recently? Do you want to make me a co-contributor on this so I can help?

**Comment by IvanJosipovic** [comment]
I have posted an updated in #330. @conficient thank you for volunteering to help, do you mind posting in #330.
