### ISSUE TITLE
Is BlazorTable supported on a hosted webassembly

### ISSUE THREAD

**Issue by jcasement** [IvanJosipovic/BlazorTable#370]
@IvanJosipovic  Is this component supported on a hosted webassembly?  Do you have any detail on what needs to be amended on the code.  I've tried your suggestions on the Read.me but I can't find where to add the third bullet point change:
Add BlazorTable Nuget
dotnet add package BlazorTable  -- **I added to the Server project**
Add to the index.html or _Hosts.cshtml
<script src="_content/BlazorTable/BlazorTable.min.js"></script>  -- **I added to the index.html on the Server project**
Add call to Program.cs or Startup.cs
Services.AddBlazorTable();  -- **can't see where to add this: Client or Server?**

**Comment by IvanJosipovic** [comment]
Please check the Sample WASM project, https://github.com/IvanJosipovic/BlazorTable/tree/master/src/BlazorTable.Sample.Wasm

**Comment by jcasement** [comment]
@IvanJosipovic  will do -- I initially started to look thru this but thought I'd ask first.  Thanks
