### ISSUE TITLE
Enable template-less columns to simplify markup?

### ISSUE THREAD

**Issue by conficient** [IvanJosipovic/BlazorTable#38]
I really like this repo! I was considering writing something like this and it would be pretty similar to what you've done already (though perhaps not as good!).

I see in the code that each column has to have a `<Template>` to render and in many cases all you do is emit the value, e.g. `@context.id` - this does make for a lot of boilerplate code that does a default operation which perhaps could be avoided?

Could I suggest that if the `Template` is null, the code tries to render the value in this manner by default? Optionally it could also have a `Format` attribute on the column to indicate how the Table should try to render the object, e.g. for a decimal value it might be `Format="$#,##0.00"` ?

I'll have a play in my fork and see if I can put together a pull request for this. Any suggestions or ideas welcome.

**Comment by conficient** [comment]
Have created a branch in my fork to try this out, seems to work okay. 

Modified the `Table` component to check for a null `Template` and call a `.Render` method on the `Column`. 

The first two columns in the [Sample Page](https://github.com/conficient/BlazorTable/blob/templateless-rendering/src/BlazorTable.Sample/Pages/Index.razor) can now look like this:
```html
    <Column TableItem="PersonData" Title="Id" Field="@(x => x.id)" Sortable="true" Filterable="true" Width="10%" />
    <Column TableItem="PersonData" Title="Full Name" Field="@(x => x.full_name)" Sortable="true" Filterable="true" Width="20%" />
```
I also added a `Format` parameter so the `price` property can be formatted:
```html
    <Column TableItem="PersonData" Title="Price" Field="@(x => x.price)" Sortable="true" Filterable="true" Width="10%" Format="#,##0.00" />
```
I used `string.Format` and `Field.Compile` to get and render the value but I'm not 100% happy this is the best approach? Comments welcome

**Comment by IvanJosipovic** [comment]
Thank you very much for taking the time to help out. This is a very useful feature.

I reviewed your branch and it looks great. I can't think of a better way to handle the string.Format/Field.Compile.

Please shoot the PR whenever you get a chance.

**Comment by conficient** [comment]
OK will do, thanks!
