### ISSUE TITLE
Warning on `UnknownParameters`

### ISSUE THREAD

**Issue by conficient** [IvanJosipovic/BlazorTable#41]
I noticed there is a compiler warning on
```
        [Parameter(CaptureUnmatchedValues = true)]
        public IDictionary<string, object> UnknownParameters { get; set; }
```
of `Change 'UnknownParameters' to be read-only by removing the property setter.` - That seemed odd since it has to be settable. I checked the Blazor code at [InputBase.cs](https://github.com/aspnet/AspNetCore/blob/master/src/Components/Web/src/Forms/InputBase.cs) - Steve used an `IReadOnlyDictionary` here which removes that warning.

**Comment by IvanJosipovic** [comment]
Fixed in, https://github.com/IvanJosipovic/BlazorTable/pull/44/commits/5f6aa1a53e2329b0be58070921f2e92dda5d95cc
Thank you
