### ISSUE TITLE
Table shows no items if you don't enter a page size

### ISSUE THREAD

**Issue by Js41637** [IvanJosipovic/BlazorTable#47]
Not really an issue but it did confuse me for a few minutes :)

Probably should have a default set?

Also do you think there should be a way to always show everything? Apart from entering a very high number that is... or just using the row count. Not really an issue I suppose.

Thanks.

**Comment by conficient** [comment]
I just ran into this one as well.. if it's not set then perhaps paging should be off.

**Comment by conficient** [comment]
Just putting together a PR for this. Proposed design is:

1. If no `PageSize` is specified in the `<Table>` it defaults to 10 rows? Or zero?
2. If `PageSize` is set to zero, paging is turned off and all rows are returned

Opinions?
