### ISSUE TITLE
Filtering popup shows in incorrect position when rendering server side

### ISSUE THREAD

**Issue by Js41637** [IvanJosipovic/BlazorTable#48]
I assume this issue is related to it running server side. I'm not sure how much server side support you have at the moment but normal rendering of the table works fine as well as sorting and pagination.

If you open the filter popup it shows at the top left of the page as it doesn't know where to go.

**Comment by IvanJosipovic** [comment]
Have you correctly referenced the JavaScript?

`<script src="_content/BlazorTable/BlazorTable.min.js"></script>`

There is working server side example in the project, see below:
https://github.com/IvanJosipovic/BlazorTable/tree/master/src/BlazorTable.Sample.Server

**Comment by Js41637** [comment]
Ah sorry, I should have looked more closely. This does fix the issue.

Does this code only container the Popper logic because I do already have Popper.js loaded.
I do see this on the roadmap though so I guess it's not an issue at the moment.

Thanks.
