### ISSUE TITLE
Navigation from Field

### ISSUE THREAD

**Issue by MarkKennedyAveva** [IvanJosipovic/BlazorTable#50]
Any ideas on a NavLink within a TableItem to navigate on selection of a column/row item?

**Comment by conficient** [comment]
This is pretty simple to implement with the current BlazorTable, just use a link within the Template for a column, e.g.
```
    <Column TableItem="PersonData" Title="Actions" >
        <Template> 
            <a href="@context.SomeUrl">View @context.last_name"</a>
        </Template>
    </Column>
```
