### ISSUE TITLE
Filter popup flicker

### ISSUE THREAD

**Issue by taluis** [IvanJosipovic/BlazorTable#56]
The source version of the Filter popup will temporarily display in the upper left of the table grid on the webpage and then (correctly) re-position itself beneath the column. However, the demo version 1.0.5 does not. Is the source code in GitHub up to date? I notice that it still says version 1.0.0. Thanks.

**Comment by IvanJosipovic** [comment]
The demo version is running Blazor Wasm, I assume that you're using Blazor Server Side, due to the "lag" in Blazor SSB, the repositioning is visible. I'm hoping to resolve this at some point by switching the popup to use css rather than popper.js

Master is up to date with the nuget.

**Comment by taluis** [comment]
Thanks, that explains it clearly. I appreciate the response and the software.
