### ISSUE TITLE
Feature: EmptyDataTemplate

### ISSUE THREAD

**Issue by conficient** [IvanJosipovic/BlazorTable#57]
I'm going to create a PR for the EmptyDataTemplate feature. My proposed design is as follows:

-  `EmptyDataTemplate` is an optional render fragment

 - If a BlazorTable dataset has no rows and an EmptyDataTemplate is defined, this should be rendered, replacing the current static text `<h1>No items....</h1>`. It would still be rendered inside a single row+cell spanning the table width.

 - If there is no EmptyDataTemplate set then nothing is rendered after the header row.

**Comment by IvanJosipovic** [comment]
Sounds good

**Comment by IvanJosipovic** [comment]
Released in version 1.0.9 and I added support for LoadingDataTemplate. Thanks for your help.
