### ISSUE TITLE
Highlight selected row

### ISSUE THREAD

**Issue by taluis** [IvanJosipovic/BlazorTable#62]
Here is how I got the selected row to be highlighted:

1. On Table.razor.cs, add the following:

      internal int SelectedRow { get; set; } = -1;
      internal void RowClicked(int rowIndex)
      {
           SelectedRow = rowIndex;
           StateHasChanged();
      }

2. On Table.razor, modify the following:

   if (TempItems.Any())
   {
      **int ith = 0;**
      foreach (TableItem item in TempItems)
      {
         **int rowIndex = ith;**
         **<tr @key="item" class="@(SelectedRow == rowIndex ? "table-primary" : "")" @onclick="() => RowClicked(rowIndex)" @onclick:stopPropagation>**
            @foreach (IColumn<TableItem> column in Columns)

**Comment by taluis** [comment]
I forgot to include the increment of ith at the end of the foreach, as follows:

                  </tr>
                  ith++;
               }  // end of foreach

**Comment by IvanJosipovic** [comment]
I have added support for row selection in https://github.com/IvanJosipovic/BlazorTable/releases/tag/v1.5.0

See example, https://blazortable.netlify.com/Row
