### ISSUE TITLE
Consider adding non-generic `ITable` interface so child content does not have to use `TableItem`

### ISSUE THREAD

**Issue by conficient** [IvanJosipovic/BlazorTable#66]
While working on `EmptyDataTemplate` I realised that the `TypeParam` on this component, and the `Pager` are redundant. However they are used to register with the parent table via the `CascadingParameter`  `ITable<TableItem>`

It occurred to me that we could also implement a lower interface `ITable` (which `ITable<TableItem>` implements) for non-type specific components.

I can put a pull request together if you wish to demo this.

**Comment by conficient** [comment]
Have created a branch to explain more clearly what I'm suggesting:
https://github.com/conficient/BlazorTable/commit/7933d5ca76c71d8059c8ef6c9ef52cdc527ce92f 

In the case of `Pager` and `EmptyDataTemplate` the row type `TableItem` isn't required, so splitting th e `ITable` interface into two (one generic, the other not), it's no longer required.

**Comment by IvanJosipovic** [comment]
Great suggestion, implemented in https://github.com/IvanJosipovic/BlazorTable/commit/059408c681dbca5dcea594a6b01fd16fbd592d7c.
Thank you
