### ISSUE TITLE
Issue when Integrating BlazorTable 1.1.0 blazor component in aspnet core3.1 razor page

### ISSUE THREAD

**Issue by shitalumare** [IvanJosipovic/BlazorTable#74]
I am using BlazorTable component in my core3.1 razor application  and I have added below changes

<base href="/" /> 
<script src="/_framework/blazor.server.js"></script>
BlazorTable.min.js
 to layout page.
MapBlazorHub() and AddServerSideBlazor() to Startup
Added component  razor page
But I am facing below issues :

Information: Normalizing '_blazor' to 'https://localhost:44349/_blazor'.   blazor.server.js:1
 Information: WebSocket connected to wss://localhost:44349/_blazor?id=9wnA2r08fNJCHJ45sDWimg.
Error: The list of component records is not valid.
 Information: Connection disconnected.
 Uncaught (in promise) Error: Invocation canceled due to the underlying connection being closed.
    at e.connectionClosed (blazor.server.js:1)
    at e.connection.onclose (blazor.server.js:1)
    at e.stopConnection (blazor.server.js:1)
    at e.transport.onclose (blazor.server.js:1)
    at e.close (blazor.server.js:1)
    at e.stop (blazor.server.js:1)
    at e.<anonymous> (blazor.server.js:1)
    at blazor.server.js:1
    at Object.next (blazor.server.js:1)
    at a (blazor.server.js:1)

2) I have column Roles with multiple rows but it is giving error when i tried to loop to get each rolename.  public class PersonData  {   public ICollection<RoleViewModel> Roles { get; set; } } <Column TableItem="PersonData" Title="Role" Field="@(x => x.Roles)" Sortable="true" Filterable="true" Width="10%">     </Column>

**Comment by IvanJosipovic** [comment]
Could you please provide a larger sample code base that exhibits this issue? I am not able to understand the problem from the info provided.

**Comment by shitalumare** [comment]
Hi,
I want to bind personData table item which is having collection of Roles.
public class PersonData { 
public string full_name { get; set; }
public ICollection Roles { get; set; }
 }
public class Roles
{
 public int RoleId { get; set; }
public string RoleName { get; set; }
}
But i am not able to display collection of roles for that particular person using BlazorTable.
Table TableItem="PersonData " Items="UserList" PageSize="5" ColumnReorder="true">
    <Column TableItem="PersonData " Title="First Name" Field="@(x => x.full_name )" Sortable="true" Filterable="true" Width="10%" DefaultSortColumn="true" />
 <Column TableItem="PersonData " Title="Role" Field="@(x => x.Roles)" Sortable="true" Filterable="true" Width="10%">
    </Column>

2. My another issue is : 
I am getting below error on console and paging sorting and filtering not working.

Information: Normalizing '_blazor' to 'https://localhost:44349/_blazor'.   blazor.server.js:1
 Information: WebSocket connected to wss://localhost:44349/_blazor?id=9wnA2r08fNJCHJ45sDWimg.
Error: The list of component records is not valid.
 Information: Connection disconnected.
 Uncaught (in promise) Error: Invocation canceled due to the underlying connection being closed.
    at e.connectionClosed (blazor.server.js:1)
    at e.connection.onclose (blazor.server.js:1)
    at e.stopConnection (blazor.server.js:1)
    at e.transport.onclose (blazor.server.js:1)
    at e.close (blazor.server.js:1)
    at e.stop (blazor.server.js:1)
    at e.<anonymous> (blazor.server.js:1)
    at blazor.server.js:1
    at Object.next (blazor.server.js:1)
    at a (blazor.server.js:1)

**Comment by IvanJosipovic** [comment]
Please see the working Blazor Server example in the source code, https://github.com/IvanJosipovic/BlazorTable/tree/master/src/BlazorTable.Sample.Server
