### ISSUE TITLE
Server-Side

### ISSUE THREAD

**Issue by luvssti** [IvanJosipovic/BlazorTable#76]
Hi, I just want to ask if how to make a server side paging?

Thank You!

**Comment by IvanJosipovic** [comment]
I have not started this feature yet, however, it is on the roadmap https://github.com/IvanJosipovic/BlazorTable/issues/39

**Comment by chbjh** [comment]
Hey @IvanJosipovic do you have an ETA for this?

This is an absolutely essential feature when working with large amounts of data.

Thanks.

**Comment by thangchung** [comment]
Yes, that should be on the stable version because when we build the product, especially in admin pages, then we always need to do paging on the server-side.
