### ISSUE TITLE
Search value in all columns

### ISSUE THREAD

**Issue by rojasjo** [IvanJosipovic/BlazorTable#95]
Hello everybody,

First of all, I think that this repository is awesome.

I use to use JQuery Datatable in my web projecs but since I would like to move to blazor webassembly I was searching for a library written in C# and I have found this repository that I was able to intregate very smoothly in my solution.

I would like to ask if you are thinking about a search field like the one that JQuery Datatable has.
![immagine](https://user-images.githubusercontent.com/22415328/77649584-603c4300-6f6a-11ea-8c47-ceef11ac5df7.png)

Thank you for the nice job!

**Comment by IvanJosipovic** [comment]
Global Search is on the Roadmap https://github.com/IvanJosipovic/BlazorTable/issues/39, I have not started on this feature yet.

**Comment by rojasjo** [comment]
Thank you for your reply!

**Comment by IvanJosipovic** [comment]
I have added Global Search to the latest release [1.6.0](https://github.com/IvanJosipovic/BlazorTable/releases/tag/v1.6.0)

You can give it a test here, https://BlazorTable.netlify.com/GlobalSearch

Let me know if it works as expected.

**Comment by rojasjo** [comment]
Hello Ivan,

yes, it does. Thank you again!

**Comment by IvanJosipovic** [comment]
I also added a search bar that can be enabled in the latest release, see https://blazortable.netlify.com/GlobalSearch
