### ISSUE TITLE
CustomSelect filter doesn't provide first value in WASM

### ISSUE THREAD

**Issue by rdadkins** [IvanJosipovic/BlazorTable#97]
Minimal column:
```
<Column TableItem="Model" Title="Item" Field="@(x => x.Item)" Sortable="true" Filterable="true">
  <CustomIFilters>
    <CustomSelect TableItem="Model">
      <CustomSelectOption Key="1" Value="@("1")"/>
      <CustomSelectOption Key="2" Value="@("2")"/>
      <CustomSelectOption Key="3" Value="@("3")"/>
    </CustomSelect>
  </CustomIFilters>
</Column>
```

When a user filters on this column and selects "Is Equal To" with a value of 1 (initial value), the filter doesn't pass 1. You need to select a different value other than 1 and switch back to it for 1 to filter through. 

Obviously, an empty option would prevent this as it would force users to select a non-empty value.

**Comment by IvanJosipovic** [comment]
Thank you for reporting this issue. It should be fixed in [v1.7.2](https://github.com/IvanJosipovic/BlazorTable/releases/tag/v1.7.2)
