### ISSUE TITLE
Pager's AlwaysShow doesn't work

### ISSUE THREAD

**Issue by NetherGranite** [IvanJosipovic/BlazorTable#99]
When `Pager.AlwaysShow` is `false`, the Page is supposed to only display if there's more than one page, but as you can see here:

https://github.com/IvanJosipovic/BlazorTable/blob/f5e232156ef4226f42cfd777845401b91584248d/src/BlazorTable/Components/Pager.razor#L3

the Pager will also display if there's only one page.

**Comment by IvanJosipovic** [comment]
Thank you!
